# GitHub 配置
# Github Apps 的PrivateKey
PrivateKey:
# Github Apps 的ClientID
ClientID:
# Github Apps 的ClientSecret
ClientSecret:
# GitHub Apps 的WebhookSecret
WebhookSecret:
# Github 访问令牌
# https://github.com/settings/tokens/new
access_token: